config/routes.rb
Rails.application.routes.draw do
  get 'paginas/empresa'

  get 'paginas/localizacao'

  get 'paginas/contato'

  get 'paginas/empresa'

  get 'paginas/localizacao'

  get 'paginas/contato'

  resources :produtos

  root :to => 'paginas#empresa'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
	validates_presence_of :codigo, message: "deve ser preenchido!"
	validates_presence_of :nome, message: "deve ser preenchido!"
	validates_presence_of :modelo, message: "deve ser preenchido!"
	validates_presence_of :marca, message: "deve ser preenchida!"
	validates_presence_of :preco, message: "deve ser preenchido!"
	validates_presence_of :fabricacao, message: "deve ser preenchido!"

	validates_uniqueness_of :codigo, message: "já cadastrado!"

	validates_numericality_of :preco, message: "deve ser numérico!"

	mount_uploader :foto, FotoProdutoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def empresa
  end

  def localizacao
  end

  def contato
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:codigo, :nome, :modelo, :marca, :preco, :fabricacao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/_latbar.html.erb
<div id="wrapper">
	<div id="sidebar-wrapper">
		<ul class="sidebar-nav">
			<li class="sidebar-brand">
				<a href="#" >
					<h4>Menu</h4>
				</a>
			</li>
			<li style="font-size: 20px;">
				<%= link_to ' Empresa', paginas_empresa_path,class: "glyphicon glyphicon-home" %> </br>
			</li>
			<li style="font-size: 20px;">
				<%= link_to ' Localização', paginas_localizacao_path , class: "glyphicon glyphicon-map-marker"%> </br>
			</li>
			<li style="font-size: 20px;">
				<%= link_to ' Contato', paginas_contato_path , class: "glyphicon glyphicon-phone-alt"%> </br>
			</li>
			<li style="font-size: 20px;">
				<%= link_to ' Produtos', produtos_path , class: "glyphicon glyphicon-book"%>
			</li>
		</ul>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
			data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Brand</a>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li class="active"><a href="#">Link <span class="sr-
				only">(current)</span></a></li>
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
					aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#">Link</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
					aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Separated link</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja de Informática</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/navbar" %>
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= render "layouts/latbar" %>
			</div>
			<div class="col-md-9">
				<div class="panel-body">
					<%= yield %>
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
				</div>
			</div>
		</div> <!-- row -->
	</div> <!-- container -->
	
	<%= yield %>

</body>
</html>

app/views/paginas/contato.html.erb
<h1>Nossos Contatos</h1>
<p>
	<b> Campos dos Goytacazes: </b> 2726-2524
</p>
</br>
<p>
	<b> São Francisco de Itabapoana: </b> 2789-1011
</p>
</br>
<p>
	<b> São João da Barra: </b> 2741-4243
</p>
</br>
<p>
	<b> Whatsapp: </b> 99988-7766
</p>
</br>
<p>
	<b> Email: </b> contato@lojainformatica.com.br
</p>

app/views/paginas/empresa.html.erb
<h1>A Empresa</h1>
<p> A <b> Loja de Informática </b>, empresa que se destaca no mercado de informática em todo Norte Fluminense pela qualidade de seus produtos e serviços, possui um grande portfólio de soluções que atende à demanda de toda região sempre atenta as novas tendências de Mercado.</p>

app/views/paginas/localizacao.html.erb
<h1>Nossos Endereços</h1>
<p>
	<b> Campos dos Goytacazes: </b> </br> Rua João Pessoa, Nº 123, Centro.
</p>
<p>
	<b> São Francisco de Itabapoana: </b> </br> Avenida Afonso Celso, Nº 456, Centro.
</p>
<p>
	<b> São João da Barra: </b> </br> Rua São João, Nº 789, Centro.
</p>

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :fabricacao %><br>
    <%= f.text_field :fabricacao , class: 'datepicker' %>
  </div>
  <div>
    <%= f.label :foto %>
    <%= image_tag @produto.foto_url, class: 'foto' if @produto.foto? %>
    <%= f.file_field :foto, label: 'Foto' , input_html: {accept: ('application/jpg') } %> <br/>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
<%= link_to ' Voltar', produtos_path , class: "btn btn-default " %>
  </div>
<% end %>

<script type="text/javascript">

$(document).ready(function(){
  $('.datepicker').datepicker({format: 'dd-mm-yyyy'});
});

</script>

app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h3> Produtos </h3>

<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Modelo</th>
      <th>Marca</th>
      <th>Preço</th>
      <th>Fabricação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.codigo %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.modelo %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.preco %></td>
        <td><%= link_to ' ', produto, class: "glyphicon glyphicon-list-alt" %></td>
        <td><%= link_to ' ', edit_produto_path(produto), class: "glyphicon glyphicon-pencil" %></td>
        <td><%= link_to ' ', produto, method: :delete, data: { confirm: 'Você tem certeza?' } , class: "glyphicon glyphicon-trash" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código:</strong>
  <%= @produto.codigo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @produto.modelo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Fabricação:</strong>
  <%= @produto.preco %>
</p>


<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>